taskkill /f /t /IM RadeonSoftware.exe
taskkill /f /t /IM amdfendrsr.exe
taskkill /f /t /IM atieclxx.exe
taskkill /f /t /IM atiesrxx.exe
taskkill /f /t /IM atiesrxx.exe
taskkill /f /t /IM AMDNoiseSuppression.exe
taskkill /f /t /IM amdow.exe
taskkill /f /t /IM AMDRSServ.exe
taskkill /f /t /IM CPUMetricsServer.exe
taskkill /f /t /IM AMDRSSrcExt.exe
taskkill /f /t /IM cncmd.exe
taskkill /f /t /IM AMDGameConfigServ.exe